function [fitresult_normal_g42, gof] = createFit_intropolation_normal(Voltage, Lux, Current)
%CREATEFIT(VOLTAGE,LUX,CURRENT)
%  Create a fit.
%
%  Data for 'Interpolant_fit_normal' fit:
%      X Input : Voltage
%      Y Input : Lux
%      Z Output: Current
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Aug-2014 11:25:06


%% Fit: 'Interpolant_fit_normal'.
[xData, yData, zData] = prepareSurfaceData( Voltage, Lux, Current );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult_normal_g42, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Interpolant_fit_normal' );
h = plot( fitresult_normal_g42, [xData, yData], zData );
legend( h, 'Interpolant_fit_normal', 'Current vs. Voltage, Lux', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Voltage' );
ylabel( 'Lux' );
zlabel( 'Current' );
grid on
view( 23.5, 40.0 );


