function [fitresult, gof] = createFit4(Voltage, Lux, Current)
% change fitresult - to some welldefined name
%CREATEFIT4(VOLTAGE,LUX,CURRENT)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : Voltage
%      Y Input : Lux
%      Z Output: Current
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Aug-2014 20:00:37


%% Fit: 'untitled fit 2'.
[xData, yData, zData] = prepareSurfaceData( Voltage, Lux, Current );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 2', 'Current vs. Voltage, Lux', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Voltage' );
ylabel( 'Lux' );
zlabel( 'Current' );
grid on


