function [fitresult, gof] = createFit(Voltage, Lux, Current)
%CREATEFIT(VOLTAGE,LUX,CURRENT)
%  Create a fit.
%
%  Data for 'Lux_15aug' fit:
%      X Input : Voltage
%      Y Input : Lux
%      Z Output: Current
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Aug-2014 10:24:57


%% Fit: 'Lux_15aug'.
[xData, yData, zData] = prepareSurfaceData( Voltage, Lux, Current );

% Set up fittype and options.
ft = fittype( 'loess' );
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Lux_15aug' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Lux_15aug', 'Current vs. Voltage, Lux', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Voltage' );
ylabel( 'Lux' );
zlabel( 'Current' );
grid on
view( 33.5, 14.0 );


