function [fit_normal_voc, gof] = Gen_voc_line(LUX_oc,Voc )
%CREATEFIT(VOC,LUX_OC)
%  Create a fit.
%
%  Data for 'V_oc_Fit' fit:
%      X Input : Voc
%      Y Output: LUX_oc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Aug-2014 12:43:35


%% Fit: 'V_oc_Fit'.
[xData, yData] = prepareCurveData( LUX_oc,Voc );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.99999999035934;

% Fit model to data.
[fit_normal_voc, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'V_oc_Fit' );
h = plot( fit_normal_voc, xData, yData );
legend( h, 'LUX_oc vs. Voc', 'V_o_c Fit', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Voc' );
ylabel( 'LUX_o_c' );
grid on


